test.object ("cron.Api.Context", true, "scheduler")
    .should ("have a scheduler getter")
        .up (s => s.server = nit.new ("http.Server"))
        .up (s => s.args = nit.require ("http.Context")
            .new ()
            .registerScope ("server", s.server)
        )
        .returnsInstanceOf ("cron.Scheduler")
        .commit ()
;
