test.object ("cron.Api.Context", true, "scheduler")
    .should ("have a scheduler getter")
        .given (nit.require ("http.Context").new ())
        .before (s => s.args[0].server = nit.new ("http.Server"))
        .after (s => s.mock = test.mock (s.result, "stop"))
        .expectingPropertyToBe ("args.0.server.listeners.http\\.Server\\.stop.length", 1)
        .expecting ("the scheduler stops when the server stops", async (s) => !!(await s.args[0].server.emit ("stop")))
        .expectingPropertyToBe ("mock.invocations.length", 1)
        .commit ()
;
