test.method ("cron.serverplugins.Scheduler", "preInit")
    .should ("initialize a scheduler")
    .given (nit.new ("http.Server"))
    .after (s => s.scheduler = s.Scheduler.get (s.args[0]))
    .after (s => s.mock = test.mock (s.scheduler, "stop"))
    .expectingPropertyToBe ("args.0.listeners.http\\.Server\\.stop.length", 1)
    .expecting ("the scheduler stops when the server stops", async (s) => !!(await s.args[0].emit ("stop")))
    .expectingPropertyToBe ("mock.invocations.length", 1)
    .commit ()
;
